import re

def clean_paste(data):

    data = re.sub(r'<!DOCTYPE html>'                                                                                                                                         
                        , r'<?xml version="1.0" encoding="UTF-8" ?>\r\t<rss version="2.0"\r\txmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"\r\txmlns:content="http://purl.org/rss/1.0/modules/content/"\r\txmlns:wfw="http://wellformedweb.org/CommentAPI/"\r\txmlns:dc="http://purl.org/dc/elements/1.1/"\r\txmlns:wp="http://wordpress.org/export/1.2/"\r\t>\r\t<channel>\r\t\t<title>Hakai Magazine</title>\r\t\t<link>http://hakaimagazine.com</link>\r\t\t<description>Coastal science and societies</description>\r\t\t<pubDate>Wed, 23 Aug 2017 22:09:13 +0000</pubDate>\r\t\t<language>en-US</language>\r\t\t<wp:wxr_version>1.2</wp:wxr_version>\r\t\t<wp:base_site_url>http://hakaimagazine.com</wp:base_site_url>\r\t\t<wp:base_blog_url>http://hakaimagazine.com</wp:base_blog_url>\r\t\t<wp:author>\r\t\t\t<wp:author_id>1</wp:author_id>\r\t\t\t<wp:author_login><![CDATA[hakaimagazine]]></wp:author_login>\r\t\t\t<wp:author_email><![CDATA[info@hakaimagazine.com]]></wp:author_email>\r\t\t\t<wp:author_display_name><![CDATA[hakaimagazine]]></wp:author_display_name>\r\t\t\t<wp:author_first_name><![CDATA[Hakai]]></wp:author_first_name>\r\t\t\t<wp:author_last_name><![CDATA[Magazine]]></wp:author_last_name>\r\t\t</wp:author>\r\t\t<generator>https://wordpress.org/?v=4.8</generator>\r\t\t\r\t<item>\r<junktagstart>', data)

    data = re.sub(r'  <title>(.*) \| Hakai Magazine</title>\n'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                        , r'\r<junktagend>\r\t\t<title>\1</title>\r\t\t<dc:creator><![CDATA[hakaimagazine]]></dc:creator>\r\t\t<description></description>\r<junktagstart>', data)

    data = re.sub(r'<h2><div class="field field-name-field-dek field-type-text-long field-label-hidden"><div class="field-items"><div class="field-item even"><p>(.*)</p>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        , r'\r<junktagend>\t\t<excerpt:encoded><![CDATA[\1]]></excerpt:encoded>\r\t\t<wp:postmeta>\r\t\t\t<wp:meta_key><![CDATA[deck]]></wp:meta_key>\r\t\t\t<wp:meta_value><![CDATA[\1]]></wp:meta_value>\r\t\t</wp:postmeta><junktagstart>', data)

    data = re.sub(r'<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="(.*)T(.*)">Published [a-zA-Z \d,]*</span></div></div></div><div class="field field-name-field-series field-type-taxonomy-term-reference field-label-hidden"><div class="field-items"><div class="field-item even"><span class="series__prefix">Part of our </span><a href="/series/([a-zA-Z\-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([\&\#a-zA-Z\- \d\;]*)</a><span class="series__suffix"> series</span></div></div></div><div class="field field-name-field-body field-type-text-long field-label-hidden"><div class="field-items"><div class="field-item even">'
                        , r'\r<junktagend>\r\t\t<wp:post_date><![CDATA[\1 00:00:00]]></wp:post_date>\r\t\t<wp:post_date_gmt><![CDATA[\1 00:00:00]]></wp:post_date_gmt>\r\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>\r\t\t<wp:status><![CDATA[publish]]></wp:status>\r\t\t<wp:post_parent>0</wp:post_parent>\r\t\t<wp:menu_order>0</wp:menu_order>\r\t\t<wp:postmeta>\r\t\t\t<wp:meta_key><![CDATA[series]]></wp:meta_key>\r\t\t\t<wp:meta_value><![CDATA[\4]]></wp:meta_value>\r\t\t</wp:postmeta><contentstartinghere>', data)

    data = re.sub(r'<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="(.*)T(.*)">Published [a-zA-Z \d,]*</span>'
                        , r'\r<junktagend>\r\t\t<wp:post_date><![CDATA[\1 00:00:00]]></wp:post_date>\r\t\t<wp:post_date_gmt><![CDATA[\1 00:00:00]]></wp:post_date_gmt>\r\t\t<wp:ping_status><![CDATA[closed]]></wp:ping_status>\r\t\t<wp:status><![CDATA[publish]]></wp:status>\r\t\t<wp:post_parent>0</wp:post_parent>\r\t\t<wp:menu_order>0</wp:menu_order><contentstartinghere>', data)

    data = re.sub(r'<contentstartinghere>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        , r'\r\t\t<content:encoded><![CDATA[', data)

    data = re.sub(r'</div></div></div><div class="field field-name-field-share-buttons field-type-blockreference field-label-hidden">'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        , r'\r\t\t]]></content:encoded>\r<junktagstart>\r', data)

    data = re.sub(r'<div class="field field-name-field-profile-bio field-type-text-long field-label-hidden">(.*)\n</div></div></div>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        , r'\r<junktagend>\r\t\t<content:encoded><![CDATA[\1]]></content:encoded>\r<junktagstart>\r', data)

    data = re.sub(r'<div class="field field-name-field-links field-type-link-field field-label-hidden"><div class="field-items"><div class="field-item even"><a href="([\S]*)" target="_blank" rel="nofollow">([\S]*)</a></div>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        , r'\r<junktagend>\r\t\t<wp:postmeta>\r\t\t<wp:meta_key><![CDATA[website]]></wp:meta_key>\r\t\t\t<wp:meta_value><![CDATA[\1]]></wp:meta_value>\r\t\t</wp:postmeta>\r<junktagstart>\r', data)

    data = re.sub(r'<div class="field-item odd"><a href="https://twitter.com/([a-zA-Z]*)" target="_blank" rel="nofollow">twitter.com/LawtonRebeccaC</a></div></div></div>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        , r'\r<junktagend>\r\t\t<wp:postmeta>\r\t\t<wp:meta_key><![CDATA[twitter]]></wp:meta_key>\r\t\t\t<wp:meta_value><![CDATA[\1]]></wp:meta_value>\r\t\t</wp:postmeta>\r<junktagstart>\r', data)

    data = re.sub(r'<a href="/geographic-region/([a-zA-Z\s\-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z\s\-]*)</a>'                                                                                                                                                                                                                                                                                                                                                                                             
                        , r'\r<junktagend>\r\t\t<category domain="geographicregion" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data)

    data = re.sub(r'<a href="/oceanographic-region/([a-zA-Z\s\-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z\s\-]*)</a>'                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'\r<junktagend>\r\t\t<category domain="oceanographicregion" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data)

    data = re.sub(r'<a href="/scientific-fielddiscipline/([a-zA-Z\s\-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z\s\-]*)</a>'
                         , r'\r<junktagend>\r\t\t<category domain="discipline" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data) 

    data = re.sub(r'<a href="/species/([a-zA-Z\s\-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z\s\-]*)</a>'
                        , r'\r<junktagend>\r\t\t<category domain="species" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data)  

    data = re.sub(r'<a href="/topic/([a-zA-Z \-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z\&\;\# \-]*)</a>'
                        , r'\r<junktagend>\r\t\t<category domain="topic" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data)    

    data = re.sub(r'<a href="/topic/([a-zA-Z \-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z \-]*)</a>'
                        , r'\r<junktagend>\r\t\t<category domain="topic" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data)  

    data = re.sub(r'<a href="/column/([a-zA-Z\s\-]*)" typeof="skos:Concept" property="rdfs:label skos:prefLabel" datatype="">([a-zA-Z\s\-]*)</a>'
                        , r'\r<junktagend>\r\t\t<category domain="column" nicename="\1"><![CDATA[\2]]></category>\r<junktagstart>\r', data)  

    data = re.sub(r'<div class="field-content">Latitude: ([-\d\.]{0,9})(\d*) <br/>Longitude: ([-\d\.]{0,9})(\d*)</div>'
                        , r'\r<junktagend>\r\t\t<wp:postmeta>\r\t\t\t<wp:meta_key><![CDATA[geolocation]]></wp:meta_key>\r\t\t\t<wp:meta_value><![CDATA[a:3:{s:7:"address";s:19:"\1 \3";s:3:"lat";s:9:"\1\2";s:3:"lng";s:19:"\3\4";}]]></wp:meta_value>\r\t\t</wp:postmeta>\r\t\t<wp:postmeta>\r\t\t\t<wp:meta_key><![CDATA[geocode_to_paste_into_map]]></wp:meta_key>\r\t\t\t<wp:meta_value><![CDATA[\1 \3]]></wp:meta_value>\r\t\t</wp:postmeta>\r<junktagstart>\r', data)
    data = re.sub(r'<!-- /content -->'
                         , r'<junktagend>\r</item>\r</channel>\r</rss>\r<endoffile>', data)


    #delete anything between each flag
    data = re.sub(r'<junktagstart>[\s\S]*?<junktagend>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        , r'', data) 

    #clean up data
    data = re.sub(r'<endoffile>[\s\S]*'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<!--\[if IE 9\]><video style="display: none;"><!\[endif\]-->(\s\S.*)(\s\S.*)(\s\S.*)\n<!--\[if IE 9\]><\/video><!\[endif\]-->'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<(?:figure|picture)[^>]*>[\s\S]*?<img (?:.*)https:\/\/www.hakaimagazine.com\/sites\/default\/files\/(?:styles\/)*(?:[\w]+\/)*(?:[\w]+\/)*([-\w.\/]+)(?:.*)\/>[\s\S]*?<(?:figcaption|p)>(.+)<\/(?:p|figcaption)>(?:[\s\S]*?)'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'[caption align="aligncenter" width="1200"]<a href="/wp-content/uploads/\1"><img class="size-large" src="/wp-content/uploads/\1" alt="\2" width="1200" /></a>\2[/caption]', data)
    data = re.sub(r'<div(?:.+)file-video-vimeo">[\s\S]+?<iframe(?:.+)src="(.*?)"[\s\S]+?<p>(.*?)</p>'
                        , r'[caption caption="\2"][embed]\1[/embed]<p class="wp-caption-text">\2</p>[/caption]', data)
    data = re.sub(r'<video[^>]*><source (?:.*?)\/sites\/default\/files\/(?:styles\/)*?(?:[\w]+\/)*?(?:([\w-]+\.\w+)|(?:[\w-]+)\/([\w-]+\.\w+))(?:.*?)\/>[\s\S]*?<\/video>[\s\S]*?<p>(.*?)<\/p>'
                        , r'[caption caption="\3"]<video autoplay muted loop preload="auto" width="100%"><source src="/wp-content/uploads/\2" type="video/mp4" /></video><p class="wp-caption-text">\3</p>[/caption]', data)
    data = re.sub(r'&nbsp;'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'target="_blank"'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'rel="nofollow"'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\s*div[^>]*>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\s*p[ |^>]*>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'\r', data)
    data = re.sub(r'<\s*section[^>]*>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\s*article[^>]*>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\/div>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\/p>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'\r', data)
    data = re.sub(r'<\/section>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\/article>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\s*picture[^>]*>' 
                        , r'', data)
    data = re.sub(r'<\/picture>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'', data)
    data = re.sub(r'<\/figure>" width="1200" \/><\/a>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'</figure></a>', data)
    data = re.sub(r'\[embed\]\/\/player\.vimeo\.com'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'[embed width="600"]https://vimeo.com', data)
    data = re.sub(r'\?color=\[\/embed\]'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        , r'[/embed]', data)
    return data